#pragma once

#define IDR_LOGO 101
#define IDR_INFO_IMAGE 102
#define IDR_CLICK_SOUND 103
#define IDR_CLICK_SOUND_1 104
#define IDR_CLICK_SOUND_2 105
#define IDR_WATERMARK_IMAGE 106
#define IDR_FONT 107
#define IDR_GITHUB_INI 108
#define IDR_COMBAT_ICON 109
#define IDR_MOVEMENT_ICON 110
#define IDR_VISUALS_ICON 111
#define IDR_MISC_ICON 112
#define IDR_TERMINAL_ICON 113
#define IDR_INFO_ICON 114
#define IDR_IRC_ICON 115
#define IDR_LIKE_ICON 116
#define IDR_DOWNLOAD_ICON 117
#define IDR_CONFIG_MARKET_ICON 118
#define IDR_SPLASH_BG 300
#define IDR_SPLASH_LOGO 301
#define IDR_BLUR_PIXEL_SHADER 120
#define IDR_BLUR_VERTEX_SHADER 121
#define IDR_FONT_GOOGLE_SANS 122
#define IDR_FONT_INTER 123
#define IDR_FONT_JETBRAINS_MONO 124
#define IDR_FONT_MINECRAFT 125
#define IDR_FONT_SF_PRO 126
#define IDR_FONT_POPPINS 127
#define IDR_FONT_PLAYFAIR 128
#define IDR_TITLE_ORIGINAL 129

// Module card icons (LEGACY-style)
#define IDR_ICON_CPS          201
#define IDR_ICON_FPS          202
#define IDR_ICON_GEAR         203
#define IDR_ICON_KEYSTROKES   204
#define IDR_ICON_RENDERINFO   205
#define IDR_ICON_UNLOCKFPS    206
#define IDR_ICON_WATERMARK    207
#define IDR_ICON_ARRAYLIST    208
#define IDR_ICON_BACK         209
#define IDR_ICON_LOGO         210
#define IDR_ICON_DASHBOARD    211
#define IDR_ICON_VISUALS      212
#define IDR_ICON_MISC         213
#define IDR_ICON_LOGO_PINK    214
#define IDR_ICON_LOGO_CYAN    215
#define IDR_ICON_LOGO_GREEN   216
#define IDR_ICON_LOGO_BLUE    217
#define IDR_ICON_MOTIONBLUR   218
#define IDR_ICON_AUTOSPRINT   219
#define IDR_ICON_EDIT         220
#define IDR_ICON_CLOSEX       221
#define IDR_ICON_DISCORD      222
#define IDR_ICON_GITHUB       223
#define IDR_ICON_NOHURTCAM    224
#define IDR_ICON_DELETE       225
#define IDR_PROFILES_ICON     226








